version: "0.8"

doc_mapping:
  mode: dynamic
  field_mappings:
    - name: body
      type: object
      field_mappings:
        - name: value
          type: text

search_settings:
  default_search_fields: 
    - "body.value"

