version: "0.8"

doc_mapping:
  mode: dynamic
  field_mappings:
    - name: body
      type: object
      field_mappings:
        - name: value
          type: text
    - name: motivation
      type: text
    - name: created
      type: datetime
      fast: true
    - name: creator
      type: text
    - name: creator.name
      type: text



