version: "0.8"

doc_mapping:
  mode: dynamic
  field_mappings:
    - name: body
      type: object
      stored: true
      field_mappings:
        - name: value
          type: text
          record: position
          stored: true

search_settings:
  default_search_fields: 
    - "body.value"

